### ISSUE TITLE
Use the browser Notifications API to notify of build status changes

### ISSUE THREAD

**Issue by benvinegar** [getsentry/freight#103]
https://developer.mozilla.org/en-US/docs/Web/API/notification

**Comment by mattrobenolt** [comment]
See: https://github.com/getsentry/freight/pull/93

I forget why we ended up thinking this was bad idea.

**Comment by cameronmcefee** [comment]
Is this covered by https://github.com/getsentry/freight/pull/117?

**Comment by MaxBittker** [comment]
yes

**Comment by billyvg** [comment]
Closed by #117
