### ISSUE TITLE
500 error on heroku

### ISSUE THREAD

**Issue by akatz** [getsentry/freight#23]
When resolving auth the output of the python version breaks the app.

```
Invalid header value 'ds/0.0.0 (python 2.7.10 (default, May 27 2015, 20:38:41) \n[GCC 4.8.2])'
```

**Comment by dcramer** [comment]
Can you give the full stacktrace?

**Comment by akatz** [comment]
Do you still need the full trace?

**Comment by dcramer** [comment]
Nope was able to track down the code
