### ISSUE TITLE
Deploys stalling

### ISSUE THREAD

**Issue by dcramer** [getsentry/freight#39]
It's unclear what's causing this, but my theories are:

1. Something in the underlying task worker is failing
2. Something is causing a deadlock and completely hanging the execution

Can't introspect because Heroku. The one thing I do know is canceling the task correctly shows the message which means the execute_task handler is still functional and responsive, which means the Celery worker *should* be working fine.

The only real way to recover atm is to ps:scale worker=0 and then bring them back up.

**Comment by mattrobenolt** [comment]
This hasn't been a problem for us in a long time, and now we don't run freight on heroku. This was also likely resolved by removing Celery. So closing this.
