### ISSUE TITLE
Postgres integrity errors in LogReporter

### ISSUE THREAD

**Issue by jkimbo** [getsentry/freight#52]
I'm getting lots of errors from the `LogReporter` when it's trying to save a `LogChunk` due to unique constraints. Example:

```shell
IntegrityError: (psycopg2.IntegrityError) duplicate key value violates unique constraint "unq_logchunk_source_offset"
DETAIL:  Key (task_id, "offset")=(8, 0) already exists.
 [SQL: 'INSERT INTO logchunk (task_id, "offset", size, text, date_created) VALUES (%(task_id)s, %(offset)s, %(size)s, %(text)s, %(date_created)s) RETURNING logchunk.id'] [parameters: {'text': u"Raven is not configured (logging is disabled). Please see the documentation for more information.\n>> Running ['git', 'fetch', '--all', '-p']\nFetching origin\n", 'date_created': datetime.datetime(2015, 10, 27, 11, 1, 58, 679882), 'offset': 0, 'task_id': 8, 'size': 157}]
```

The offending code block seems to be https://github.com/getsentry/freight/blob/ec7edc5eb35e30e46cbaa1a0a1e4ac4baf23dc9f/freight/tasks/execute_task.py#L93-L108

I'm not very familiar with threads but seems that `self.cur_offset` is not being incremented correctly which is leading to the key error. Can anyone with more context help?

**Comment by dcramer** [comment]
Ah yeah thats definitely not safe. We just need to add a lock around that block.
