### ISSUE TITLE
Deploy spawning duplicate concurrent jobs

### ISSUE THREAD

**Issue by amitofs** [getsentry/freight#55]
During my investigation of https://github.com/getsentry/freight/issues/54 I found out that for each deploy triggered, multiple deploys jobs were being spawned and processed by celery.

This issue seems to have started for me with https://github.com/getsentry/freight/commit/cc2bea00582ff399bbf7ef15d800eead2a8f6cdb, the previous commit of https://github.com/getsentry/freight/commit/39f290f04153dccd00f581d27f4b6ef4504d517c is working fine.

Duplicate jobs https://github.com/getsentry/freight/commit/cc2bea00582ff399bbf7ef15d800eead2a8f6cdb:
<img width="1440" alt="spawn_multiple" src="https://cloud.githubusercontent.com/assets/2317722/11673733/0e279704-9e13-11e5-8d86-268b5f39689e.png">

Working as desired https://github.com/getsentry/freight/commit/39f290f04153dccd00f581d27f4b6ef4504d517c:
<img width="1440"  alt="spawn_single" src="https://cloud.githubusercontent.com/assets/2317722/11673732/0e24ea4a-9e13-11e5-8114-d034d3aa771e.png">

I am not too familiar with celery but happy to provide any more troubleshooting information if required.

**Comment by dcramer** [comment]
@mitsuhiko any thoughts?

We've seen weird quirks, but we're on Heroku which means we can't debug anything. I'm wondering if it's related. It could be Celery doesn't like our subprocess spawning/etc.

**Comment by thoas** [comment]
same issue here, had to downgrade to 9934cfb last week

**Comment by amitofs** [comment]
fixed by https://github.com/getsentry/freight/pull/56
